#2절 보안기능 5.암호화되지 않은 중요정보
spring:
  # datasource 설정
  datasource:
    url: jdbc:mysql://localhost:3306/boards
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

#2절 보안기능 13.하드코드된 중요정보
file:
  dir: ${user.dir}/src/main/resources/files/

# jpa 설정
#  jpa:
#    hibernate:
#      # 애플리케이션 실행시점에 엔티티 정보를 보고 테이블을 다 지우고 다시 생성 (DB에 테이블을 만들지 않아도 엔티티 정보를 보고 쫘악 생성해버림)
#      ddl-auto: create
#    properties:
#      hibernate:
#        #sytem.out
#        #show_sql: true
#        format_sql: true

# 파일 용량 제한 설정
server:
  servlet:
    multipart:
      maxFileSize: 10MB
#      maxRequestSize: 100MB

# log 설정
logging:
  level:
    #logger
    org.hibernate.SQL: debug
    #각각 파라미터가 어디 어느 속성으로 들어갔는지 로그를 찍어줌 {1}은 memberName에 .. 이런식으로
    org.hibernate.type: trace
